name: checkin

on:
  push:
    branches: 
      - main
  schedule:
    - cron: '0 15,22 * * *'

jobs:
  v-checkin:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@master
    
    - name: Set python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: python -m pip install --upgrade requests
    
    - name: v.qq.com check in
      env:
        SERVERCHAN_SCKEY: ${{ secrets.SERVERCHAN_SCKEY }}
        V_COOKIE_LOGIN: ${{ secrets.V_COOKIE_LOGIN }}
        V_COOKIE_SIGNIN: ${{ secrets.V_COOKIE_SIGNIN }}
        V_AUTH_REFRESH_URL: ${{ secrets.V_AUTH_REFRESH_URL }}
      run: python main.py
